#!/bin/bash

set -ex

# get version from env or use default
NPS_VERSION=${NPS_VERSION:-latest}
NGINX_VERSION=${NGINX_VERSION:-1.11.4}
PSOL_VERSION=${PSOL_VERSION:-1.11.33.4}

echo "Building ngx_pagespeed ${NPS_VERSION}"

UBUNTU_VERSION=`lsb_release -c | cut -f2`

# quote the / since it will go into sed
PS_NGX_EXTRA_FLAGS="--with-ld-opt=-static-libstdc++"

sudo apt-get install build-essential -y
sudo apt-get install dpkg-dev libssl-dev build-essential zlib1g-dev libpcre3 libpcre3-dev unzip checkinstall -y


# build dir
get_abs_filename() {
  # $1 : relative filename
  echo "$(cd "$(dirname "$1")" && pwd)/$(basename "$1")"
}
NGX_BUILD=$(get_abs_filename "./ngx_build")
rm -rf $NGX_BUILD
mkdir $NGX_BUILD
cd $NGX_BUILD

wget http://nginx.org/download/nginx-${NGINX_VERSION}.tar.gz
tar zxf nginx-${NGINX_VERSION}.tar.gz

# steps from https://github.com/pagespeed/ngx_pagespeed
# download pagespeed
wget https://github.com/pagespeed/ngx_pagespeed/archive/${NPS_VERSION}-stable.zip
unzip ${NPS_VERSION}-stable.zip
cd ngx_pagespeed-${NPS_VERSION}-stable/
wget https://dl.google.com/dl/page-speed/psol/${PSOL_VERSION}.tar.gz
tar -xzvf ${PSOL_VERSION}.tar.gz  # extracts to psol/
cd ..

cd nginx-${NGINX_VERSION}
./configure \
	--user=www-data \
	--group=www-data \
	 --prefix=/usr/share/nginx \
--sbin-path=/usr/sbin/nginx \
--conf-path=/etc/nginx/nginx.conf \
--error-log-path=/var/log/error.log \
--http-log-path=/var/log/access.log \
--pid-path=/run/nginx.pid \
--lock-path=/var/run/nginx.lock \
--http-client-body-temp-path=/var/lib/nginx/client_temp \
--http-proxy-temp-path=/var/lib/nginx/proxy_temp \
--http-fastcgi-temp-path=/var/lib/nginx/fastcgi_temp \
--http-uwsgi-temp-path=/var/lib/nginx/uwsgi_temp \
--http-scgi-temp-path=/var/lib/nginx/scgi_temp \
--with-cc-opt='-g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2' \
--with-ld-opt='-Wl,-z,relro -Wl,--as-needed' \
	--add-module=../ngx_pagespeed-${NPS_VERSION}-stable \
	${PS_NGX_EXTRA_FLAGS} \
	--with-http_ssl_module \
	--with-http_gzip_static_module \
	--with-pcre-jit \
	--with-http_v2_module \
	--with-http_stub_status_module \
	--with-http_realip_module \
	--with-http_auth_request_module \
	--with-ipv6

make

sudo checkinstall -D --install=no -y --pkgversion="${NGINX_VERSION}-ps-${NPS_VERSION}" make install
sudo rm -rf doc-pak
mv *.deb $NGX_BUILD/
